# Generated by Django 3.1.7 on 2021-06-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='edat',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sexe',
            field=models.CharField(default='', max_length=70),
        ),
    ]
