# Generated by Django 3.1.7 on 2021-04-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_key',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
    ]
