# Generated by Django 3.1.7 on 2021-04-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lliure',
            field=models.BooleanField(default=True),
        ),
    ]
