# Generated by Django 3.1.7 on 2021-04-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210411_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_validated',
        ),
    ]
