# Generated by Django 3.1.7 on 2021-06-14 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imatge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=70, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Llibre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_llibre', models.CharField(max_length=70)),
                ('sinopsis', models.TextField(max_length=3000)),
                ('pdf', models.FileField(upload_to='')),
                ('pdf_retall', models.FileField(blank=True, null=True, upload_to='')),
                ('textPla', models.FileField(blank=True, null=True, upload_to='')),
                ('es', models.FileField(blank=True, null=True, upload_to='')),
                ('es_retall', models.FileField(blank=True, null=True, upload_to='')),
                ('en', models.FileField(blank=True, null=True, upload_to='')),
                ('en_retall', models.FileField(blank=True, null=True, upload_to='')),
                ('pt', models.FileField(blank=True, null=True, upload_to='')),
                ('pt_retall', models.FileField(blank=True, null=True, upload_to='')),
                ('zh', models.FileField(blank=True, null=True, upload_to='')),
                ('zh_retall', models.FileField(blank=True, null=True, upload_to='')),
                ('coleccio', models.CharField(blank=True, max_length=100, null=True)),
                ('num_pagines', models.IntegerField()),
                ('comentari_it', models.TextField(blank=True, max_length=3000)),
                ('publicat', models.BooleanField(default=False)),
                ('dissenyador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dissenyador', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL)),
                ('escriptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escriptor', to=settings.AUTH_USER_MODEL)),
                ('imatges', models.ManyToManyField(blank=True, related_name='imatgesassociades', to='bookapp.Imatge')),
                ('it', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='it', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maquetacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_maquetat', models.FileField(blank=True, null=True, upload_to='')),
                ('anotacions', models.CharField(blank=True, max_length=70, null=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='')),
                ('contraportada', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_a_publicar', models.FileField(blank=True, null=True, upload_to='')),
                ('anotacions', models.CharField(blank=True, max_length=70, null=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='')),
                ('contraportada', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tematica', models.CharField(max_length=20)),
                ('descripcio_tematica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Traduccio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(blank=True, max_length=2, null=True)),
                ('pdf_traduit', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TematiquesLlibre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llibre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.llibre')),
                ('tematica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.tematica')),
            ],
        ),
        migrations.CreateModel(
            name='solicitudTraduccio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(blank=True, max_length=2, null=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editortraduccio', to=settings.AUTH_USER_MODEL)),
                ('llibre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookapp.llibre')),
            ],
        ),
        migrations.CreateModel(
            name='solicitudPublicacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotacions', models.CharField(max_length=70)),
                ('IT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itsolicitud', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editorpublicacio', to=settings.AUTH_USER_MODEL)),
                ('llibre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookapp.llibre')),
            ],
        ),
        migrations.CreateModel(
            name='solicitudMaquetacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotacions', models.CharField(max_length=70)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editormaquetacio', to=settings.AUTH_USER_MODEL)),
                ('llibre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookapp.llibre')),
                ('maquetador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maquetadorsolicitud', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='solicitudImatges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=70, null=True)),
                ('context', models.CharField(blank=True, max_length=70, null=True)),
                ('dissenyador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dissenyadorimatge', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editorbateria', to=settings.AUTH_USER_MODEL)),
                ('llibre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookapp.llibre')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missatge', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now=True, null=True)),
                ('llibre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.llibre')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Missatge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cos_missatge', models.CharField(blank=True, max_length=70, null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autormissatge', to=settings.AUTH_USER_MODEL)),
                ('destinatari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destmissatge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='llibre',
            name='maquetacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maquetacio', to='bookapp.maquetacio'),
        ),
        migrations.AddField(
            model_name='llibre',
            name='maquetador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maquetador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llibre',
            name='tematiques',
            field=models.ManyToManyField(blank=True, related_name='tematiques', through='bookapp.TematiquesLlibre', to='bookapp.Tematica'),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumpte', models.CharField(max_length=100)),
                ('cos', models.TextField()),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=100)),
                ('descripcio', models.TextField()),
                ('llibre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.llibre')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
