# Generated by Django 3.1.7 on 2021-04-12 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacio',
            name='usuari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llibre',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llibre',
            name='escriptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escriptor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llibre',
            name='tematiques',
            field=models.ManyToManyField(blank=True, related_name='tematiques', through='bookapp.TematiquesLlibre', to='bookapp.Tematica'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='usuari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentari',
            name='llibre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.llibre'),
        ),
        migrations.AddField(
            model_name='comentari',
            name='usuari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
