# Generated by Django 3.1.7 on 2021-05-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_auto_20210501_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacio',
            name='data',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
