# Generated by Django 3.1.7 on 2021-05-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_auto_20210514_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imatge',
            name='nom',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
