# Generated by Django 3.1.7 on 2021-04-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_auto_20210412_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='llibre',
            name='coleccio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='llibre',
            name='num_pagines',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
