# Generated by Django 3.1.7 on 2021-05-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_auto_20210503_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='llibre',
            name='comentari_it',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
