# Generated by Django 3.1.7 on 2021-05-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_images_solicitudimatges'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='images',
            new_name='Imatge',
        ),
        migrations.AddField(
            model_name='llibre',
            name='imatges',
            field=models.ManyToManyField(blank=True, related_name='imatgesassociades', to='bookapp.Imatge'),
        ),
    ]
