# Generated by Django 3.1.7 on 2021-05-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_auto_20210501_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacio',
            name='data',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name=''),
        ),
    ]
