# Generated by Django 3.1.7 on 2021-05-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_imatge_solicitudimatges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudimatges',
            name='context',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudimatges',
            name='nom',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
