# Generated by Django 3.1.7 on 2021-05-04 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookapp', '0003_llibre_comentari_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='llibre',
            name='it',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='it', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llibre',
            name='maquetacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maquetacio', to=settings.AUTH_USER_MODEL),
        ),
    ]
