# Generated by Django 3.1.7 on 2021-05-17 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookapp', '0004_auto_20210517_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_a_publicar', models.FileField(blank=True, null=True, upload_to='')),
                ('anotacions', models.CharField(blank=True, max_length=70, null=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='')),
                ('contraportada', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='solicitudPublicacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotacions', models.CharField(max_length=70)),
                ('IT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itsolicitud', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editorpublicacio', to=settings.AUTH_USER_MODEL)),
                ('llibre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookapp.llibre')),
            ],
        ),
    ]
