# Generated by Django 3.1.7 on 2021-05-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_auto_20210504_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='llibre',
            name='publicat',
            field=models.BooleanField(default=False),
        ),
    ]
