# Generated by Django 3.1.7 on 2021-05-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_auto_20210502_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacio',
            name='data',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
