# Generated by Django 3.1.7 on 2021-05-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_publicacio_solicitudpublicacio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llibre',
            name='portada',
        ),
    ]
