# Generated by Django 3.1.7 on 2021-06-01 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookapp', '0006_remove_llibre_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missatge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cos_missatge', models.CharField(blank=True, max_length=70, null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autormissatge', to=settings.AUTH_USER_MODEL)),
                ('destinatari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destmissatge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
