# Generated by Django 3.1.7 on 2021-05-03 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookapp', '0007_auto_20210503_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='llibre',
            name='IT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IT', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llibre',
            name='dissenyador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dissenyador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llibre',
            name='maquetador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maquetador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudimatges',
            name='dissenyador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dissenyadorimatge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudmaquetacio',
            name='maquetador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maquetadorsolicitud', to=settings.AUTH_USER_MODEL),
        ),
    ]
