# Generated by Django 3.1.7 on 2021-05-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_auto_20210503_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquetacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portada', models.ImageField(upload_to='')),
                ('contraportada', models.ImageField(upload_to='')),
                ('llibre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookapp.llibre')),
            ],
        ),
    ]
