# Generated by Django 3.1.7 on 2021-05-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0010_auto_20210504_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudimatges',
            name='context',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudimatges',
            name='nom',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
